Swap from exact substring matches to each individual word matching
dbt-labs/dbt-docs pull request #145
Opened 2020-10-10 10:01 UTC by joellabes

resolves #143 

### Description
This is a first attempt at considering each word entered in a search individually, as opposed to requiring a perfect match (`model my` or `my model` should now find `my_model`, where earlier only an exact search, including underscores, would have worked). 

I couldn't get the Docs site running locally (from looking at the stack traces, seemed to be a bunch of issues with webpack, node versions, python versions...) but I have tested that each individual piece of work behaves correctly outside of the wider Docs context.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have generated docs locally, and this change appears to resolve the stated issue
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

2020-10-10 10:27 UTC, joellabes commented on src/app/services/project_service.js
> -        var search = new RegExp(val, "i")
This was never used

2020-10-12 17:58 UTC, jtcohen6 reviewed
This is really cool @joellabes !!

I'll wait until @drewbanin can give the JS a once-over, likely next week

2020-11-24 13:33 UTC, drewbanin commented
ha - oops - thanks for your patience @joellabes - giving this a look now :D

2020-11-24 13:51 UTC, drewbanin requested changes
I love what you're going for here, but I think it's about time that we giving searching some more love! What do you think about leveraging something like [fusejs](https://fusejs.io/demo.html) here and deleting a lot of this searching logic? I kicked around fuse.js, and it looks to me like it will match the query from the original issue (#143) out of the box!

Joel, if this is something you're interested in pursuing, I'd be really happy to offer some guidance! If not, I imagine it's something that we could get to in the reasonably near future. Let me know either way!

2020-11-25 03:55 UTC, joellabes commented
I'd be so excited for search to get some love - I had an urge to rework the weighting process last week as well. Happy to have a blast with Fuse. I had dramas getting dbt running locally (Windows 🙄) but will give it another whirl - if it doesn't magically work I might have to get a hand on the initial setup!

2021-01-03 08:16 UTC, joellabes commented
I've started looking into this on #162 - still a long way from it being ready, but I'm going to close this one for now.

2022-04-05 04:24 UTC, joellabes commented
OK so 162 wound up being non-performant _and_ not very good at fuzzy search. Not a good combo. 

Since this has been sitting around waiting for a year and a bit, and works just fine, I'm going to reopen it and hopefully we can get it out into a future docs release. If someone who knows more JS wants to have a swing at fuse or some other proper search lib, I'm into it. 

But in general, dbt docs searches are only a couple of words and it's not unreasonable to just require accurate typing 😅

2022-04-06 23:58 UTC, joellabes commented
@clablot check

2022-04-25 15:00 UTC, stu-k approved these changes
Just a couple comments about using lodash functions, nothing else stands out 👍

2022-05-16 16:40 UTC, emmyoop commented
Tested this out and it seems like a big quality of life improvement! 🙌   I'll take it for another spin once you implement @stu-k's suggestions.  

Your commit from October 13, 2020 is causing the cla bot to fail because it's associated with your `joel.labes@educationperfect.com` email.  You should be able to squash down your commits and get the cla bot to pass.

2022-07-18 02:43 UTC, joellabes commented on src/app/components/search/search.js
> +            function splitQuery(query){
Yep that's a better name! Have kept the function for lowercasing purposes but have swapped out all the icky split stuff for `_.words`

2022-07-18 02:49 UTC, joellabes commented
@cla-bot check

2022-07-18 03:01 UTC, joellabes commented
@emmyoop I've applied @stu-k's suggestions now 🛠️

I couldn't get the squash to work, so just re-added the educationperfect domain to my GH account and the CLA bot is happy!

2022-07-21 16:41 UTC, emmyoop approved these changes
Great work!  Thanks for staying on it and pushing it through.  The search improvements are so so satisfying.

2022-07-21 16:41 UTC, merged