Use column.comment from catalog/database if column.description is missing
dbt-labs/dbt-docs pull request #263
Opened 2022-04-11 13:51 UTC by halvorlu

Partially resolves #128 (see below)
### Description

This will display the column description fetched from the database if there is no column description in the DBT config.
Partially resolves #128, partially because the table description is still missing.
Adding the table description would require more substantial changes, since the table description (as far as I could tell) is not found in catalog.json at the moment.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have generated docs locally, and this change appears to resolve the stated issue
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

2022-04-25 12:36 UTC, emmyoop commented on CHANGELOG.md
> +- Display column description from database if description is missing from DBT config ([#128](https://github.com/dbt-labs/dbt-docs/issues/128))
Please use all lower case when mentioning dbt 😃

2022-04-27 14:25 UTC, halvorlu commented on CHANGELOG.md
> +- Display column description from database if description is missing from DBT config ([#128](https://github.com/dbt-labs/dbt-docs/issues/128))
Sure thing

2022-04-27 14:26 UTC, halvorlu commented
@emmyoop Thanks for useful feedback!

I wasn't aware that the table description was in the catalog. I think the BigQuery adapter (which I use) doesn't fetch it from the database. Anyway, I fixed the code so that we use the comment from the catalog if it is present.

2022-04-27 20:24 UTC, halvorlu commented
Should I/we document somewhere that the descriptions are fetched from the database if not provided in the dbt config? This behavior is probably not obvious to most users.

2022-05-17 18:48 UTC, emmyoop commented
We should definitely add some documentation around this functionality.  Good call bringing it up!  We plan to release this feature with our next minor release, `1.2.0`.  Can you open up an issue over in [docs.dbt.com](https://github.com/dbt-labs/docs.getdbt.com) to add documentation to the [docs page](http://docs.getdbt.com/documentation).

2022-05-17 18:50 UTC, emmyoop requested changes
@halvorlu thanks for your patience in getting back to you on this!

I looked over the code and it's generally looking good.  However, it's applying the override to the column descriptions everywhere (models, seeds, snapshots, sources) but the table override is only happening for sources.  It's important this be consistent and predictable. 
 Since sources are the only object that dbt does not generate/own, it's the only object we want to override.

Can you please update the code so that column comments are only used for sources?

2023-01-03 01:55 UTC, closed without merging